version: '3.8'

services:

  frontend:
      image: ml-frontend
      build: ./ml-kurkkumopo-frontend
      container_name: ml-frontend
      ports:
        - 3000:3000

  backend:
      image: ml-backend
      build: ./ml-kurkkumopo-backend
      container_name: ml-backend
      ports: 
        - 5000:5000
      volumes:
        - ./model:/src/model

  training:
      image: ml-training
      build: ./ml-kurkkumopo-training
      container_name: ml-training
      volumes:
        - ./model:/src/model
        - ./imgs:/src/imgs