version: '3.8'

services:

  frontend:
      image: frontend-example
      ports: 
        - 5000:5000
      container_name: frontend-example

  backend:
      image: backend-example
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis
      container_name: backend-example
      
  redis:
    image: redis
    container_name: redis